# Generated by Django 5.2.8 on 2025-11-30 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_platform_listingplatform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingplatform',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.platform'),
        ),
    ]
