# Generated by Django 5.2.8 on 2026-01-28 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_listing_bank_account_listing_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aukro_username', models.CharField(blank=True, max_length=150, null=True)),
                ('bazos_username', models.CharField(blank=True, max_length=150, null=True)),
                ('sbazar_username', models.CharField(blank=True, max_length=150, null=True)),
                ('facebook_username', models.CharField(blank=True, max_length=150, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
