# Generated by Django 5.2.8 on 2026-02-10 15:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listing',
            unique_together={('description', 'title', 'owner')},
        ),
    ]
