# Generated by Django 5.2.8 on 2026-02-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_listing_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listing',
            unique_together=set(),
        ),
    ]
