# Generated by Django 5.2.8 on 2026-02-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_listing_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='display_phone',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='email',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='name',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='personal_pickup',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='postal',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='sale_type',
        ),
    ]
