# Generated by Django 5.2.8 on 2026-02-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_listing_bank_account_remove_listing_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingplatform',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
