# Generated by Django 5.2.8 on 2026-02-16 18:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_listingplatform_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.UniqueConstraint(fields=('owner', 'title', 'description'), name='unique_listing_per_user'),
        ),
    ]
