# Generated by Django 5.2.8 on 2026-02-17 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_listing_unique_listing_per_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listingplatform',
            unique_together={('listing', 'platform')},
        ),
    ]
