# Generated by Django 5.2.8 on 2026-03-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_listingplatform_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='aukro_username',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='bazos_username',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='facebook_username',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='sbazar_username',
        ),
        migrations.AddField(
            model_name='userdata',
            name='display',
            field=models.CharField(default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userdata',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userdata',
            name='sorting',
            field=models.CharField(default='newfirst', max_length=20),
        ),
        migrations.AddField(
            model_name='userdata',
            name='theme',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
